Fix <use> with no contents
yWorks/svg2pdf.js pull request #279
Opened 2023-12-06 16:09 UTC by edemaine

Fixes #278 by correctly checking for empty paths in `GeometryNode.prototype.getBoundingBoxCore`. Indeed, the line mentioned in https://github.com/yWorks/svg2pdf.js/issues/278#issuecomment-1842474779 had a bug that wasn't correctly checking for empty paths.

I've confirmed that this fixes #278 in my setting. I didn't add tests because I don't know how they're organized...

2023-12-07 09:12 UTC, HackbrettXXX requested changes
Thanks for the PR.

- Please add a test case. You can find how to do that [here].(https://github.com/yWorks/svg2pdf.js/blob/master/README.md#testing)
- Please revert changes to the files in dist. They are only updated as part of a release.
- Please also revert yarn.lock

2023-12-07 16:19 UTC, edemaine commented
Sorry about the extra commits. `git commit -a` is a hard habit to break. 😅 

Thanks for the README pointer. I added the test case from #278. If you'd rather a more interesting test (such as a larger output from MathJax where this occurs), or rather it integrated into the existing `svg-use` example, let me know.

2023-12-11 09:10 UTC, HackbrettXXX approved these changes
Alright. Thanks for adding the test case, looks good!

2023-12-11 09:11 UTC, merged

2023-12-11 15:41 UTC, edemaine commented
I confirmed that the new release fixes my issues. Thank you!!